# Generated by Django 4.2 on 2023-05-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Super_User',
        ),
    ]
