# Generated by Django 4.2 on 2023-05-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supuser', '0003_rename_name_super_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super_User',
            new_name='user',
        ),
    ]
